# coffeelint: disable=max_line_length

unless window?
  _fs = 'fs'
  fs = require _fs
  readFile = (filename) ->
    fs.readFileSync "#{__dirname}/#{filename}", 'utf8'

# FIXME: svgs are unoptimized when read by fs (here and in iqons)
module.exports =
  'address_book': if window? then require('./address_book.svg') else readFile 'address_book.svg'
  'alert_circle_outline': if window? then require('./alert_circle_outline.svg') else readFile 'alert_circle_outline.svg'
  'arrow_down_white': if window? then require('./arrow_down_white.svg') else readFile 'arrow_down_white.svg'
  'arrow_right_white': if window? then require('./arrow_right_white.svg') else readFile 'arrow_right_white.svg'
  'bitcoin': if window? then require('./bitcoin.svg') else readFile 'bitcoin.svg'
  'book_white': if window? then require('./book_white.svg') else readFile 'book_white.svg'
  'briefcase': if window? then require('./briefcase.svg') else readFile 'briefcase.svg'
  'browser_speed': if window? then require('./browser_speed.svg') else readFile 'browser_speed.svg'
  'cash_bag': if window? then require('./cash_bag.svg') else readFile 'cash_bag.svg'
  'cash_symbol_white': if window? then require('./cash_symbol_white.svg') else readFile 'cash_symbol_white.svg'
  'cash_symbol': if window? then require('./cash_symbol.svg') else readFile 'cash_symbol.svg'
  'checkmark': if window? then require('./checkmark.svg') else readFile 'checkmark.svg'
  'chevron_right': if window? then require('./chevron_right.svg') else readFile 'chevron_right.svg'
  'clock': if window? then require('./clock.svg') else readFile 'clock.svg'
  'close': if window? then require('./close.svg') else readFile 'close.svg'
  'desktop': if window? then require('./desktop.svg') else readFile 'desktop.svg'
  'discord': if window? then require('./discord.svg') else readFile 'discord.svg'
  'ethereum': if window? then require('./ethereum.svg') else readFile 'ethereum.svg'
  'exchange': if window? then require('./exchange.svg') else readFile 'exchange.svg'
  'gavel_white': if window? then require('./gavel_white.svg') else readFile 'gavel_white.svg'
  'globe': if window? then require('./globe.svg') else readFile 'globe.svg'
  'graph': if window? then require('./graph.svg') else readFile 'graph.svg'
  'happy_face': if window? then require('./happy_face.svg') else readFile 'happy_face.svg'
  'home': if window? then require('./home.svg') else readFile 'home.svg'
  'info_outline': if window? then require('./info_outline.svg') else readFile 'info_outline.svg'
  'laptop': if window? then require('./laptop.svg') else readFile 'laptop.svg'
  'litecoin': if window? then require('./litecoin.svg') else readFile 'litecoin.svg'
  'lock_inverted': if window? then require('./lock_inverted.svg') else readFile 'lock_inverted.svg'
  'lock_shield': if window? then require('./lock_shield.svg') else readFile 'lock_shield.svg'
  'logo_white': if window? then require('./logo_white.svg') else readFile 'logo_white.svg'
  'logo': if window? then require('./logo.svg') else readFile 'logo.svg'
  'logout': if window? then require('./logout.svg') else readFile 'logout.svg'
  'mail': if window? then require('./mail.svg') else readFile 'mail.svg'
  'menu_white': if window? then require('./menu_white.svg') else readFile 'menu_white.svg'
  'monero': if window? then require('./monero.svg') else readFile 'monero.svg'
  'neo': if window? then require('./neo.svg') else readFile 'neo.svg'
  'newspaper': if window? then require('./newspaper.svg') else readFile 'newspaper.svg'
  'people_group': if window? then require('./people_group.svg') else readFile 'people_group.svg'
  'people_white': if window? then require('./people_white.svg') else readFile 'people_white.svg'
  'person_add': if window? then require('./person_add.svg') else readFile 'person_add.svg'
  'person_checkmark': if window? then require('./person_checkmark.svg') else readFile 'person_checkmark.svg'
  'person_star': if window? then require('./person_star.svg') else readFile 'person_star.svg'
  'person_white': if window? then require('./person_white.svg') else readFile 'person_white.svg'
  'phone': if window? then require('./phone.svg') else readFile 'phone.svg'
  'pickaxe': if window? then require('./pickaxe.svg') else readFile 'pickaxe.svg'
  'profile': if window? then require('./profile.svg') else readFile 'profile.svg'
  'ps4': if window? then require('./ps4.svg') else readFile 'ps4.svg'
  'ripple': if window? then require('./ripple.svg') else readFile 'ripple.svg'
  'send': if window? then require('./send.svg') else readFile 'send.svg'
  'speedometer_white': if window? then require('./speedometer_white.svg') else readFile 'speedometer_white.svg'
  'tablet': if window? then require('./tablet.svg') else readFile 'tablet.svg'
  'wrench': if window? then require('./wrench.svg') else readFile 'wrench.svg'
  'xbox': if window? then require('./xbox.svg') else readFile 'xbox.svg'
